#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThueDia")]
	public partial class dbQuanLyDiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietDonHang(ChiTietDonHang instance);
    partial void UpdateChiTietDonHang(ChiTietDonHang instance);
    partial void DeleteChiTietDonHang(ChiTietDonHang instance);
    partial void InsertDisk_Game(Disk_Game instance);
    partial void UpdateDisk_Game(Disk_Game instance);
    partial void DeleteDisk_Game(Disk_Game instance);
    partial void InsertDonHang(DonHang instance);
    partial void UpdateDonHang(DonHang instance);
    partial void DeleteDonHang(DonHang instance);
    partial void InsertKH_DatTruoc_TieuDe(KH_DatTruoc_TieuDe instance);
    partial void UpdateKH_DatTruoc_TieuDe(KH_DatTruoc_TieuDe instance);
    partial void DeleteKH_DatTruoc_TieuDe(KH_DatTruoc_TieuDe instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertTieuDe(TieuDe instance);
    partial void UpdateTieuDe(TieuDe instance);
    partial void DeleteTieuDe(TieuDe instance);
    #endregion
		
		public dbQuanLyDiaDataContext() : 
				base(global::Data.Properties.Settings.Default.QuanLyThueDiaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyDiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this.GetTable<ChiTietDonHang>();
			}
		}
		
		public System.Data.Linq.Table<Disk_Game> Disk_Games
		{
			get
			{
				return this.GetTable<Disk_Game>();
			}
		}
		
		public System.Data.Linq.Table<DonHang> DonHangs
		{
			get
			{
				return this.GetTable<DonHang>();
			}
		}
		
		public System.Data.Linq.Table<KH_DatTruoc_TieuDe> KH_DatTruoc_TieuDes
		{
			get
			{
				return this.GetTable<KH_DatTruoc_TieuDe>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<TieuDe> TieuDes
		{
			get
			{
				return this.GetTable<TieuDe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDonHang")]
	public partial class ChiTietDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoLuongDiaThue;
		
		private double _PhiThue;
		
		private string _MaDonHang;
		
		private string _MaDia;
		
		private EntityRef<Disk_Game> _Disk_Game;
		
		private EntityRef<DonHang> _DonHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoLuongDiaThueChanging(int value);
    partial void OnSoLuongDiaThueChanged();
    partial void OnPhiThueChanging(double value);
    partial void OnPhiThueChanged();
    partial void OnMaDonHangChanging(string value);
    partial void OnMaDonHangChanged();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    #endregion
		
		public ChiTietDonHang()
		{
			this._Disk_Game = default(EntityRef<Disk_Game>);
			this._DonHang = default(EntityRef<DonHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDiaThue", DbType="Int NOT NULL")]
		public int SoLuongDiaThue
		{
			get
			{
				return this._SoLuongDiaThue;
			}
			set
			{
				if ((this._SoLuongDiaThue != value))
				{
					this.OnSoLuongDiaThueChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDiaThue = value;
					this.SendPropertyChanged("SoLuongDiaThue");
					this.OnSoLuongDiaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiThue", DbType="Float NOT NULL")]
		public double PhiThue
		{
			get
			{
				return this._PhiThue;
			}
			set
			{
				if ((this._PhiThue != value))
				{
					this.OnPhiThueChanging(value);
					this.SendPropertyChanging();
					this._PhiThue = value;
					this.SendPropertyChanged("PhiThue");
					this.OnPhiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					if (this._DonHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					if (this._Disk_Game.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disk_Game_ChiTietDonHang", Storage="_Disk_Game", ThisKey="MaDia", OtherKey="MaDia", IsForeignKey=true)]
		public Disk_Game Disk_Game
		{
			get
			{
				return this._Disk_Game.Entity;
			}
			set
			{
				Disk_Game previousValue = this._Disk_Game.Entity;
				if (((previousValue != value) 
							|| (this._Disk_Game.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Disk_Game.Entity = null;
						previousValue.ChiTietDonHangs.Remove(this);
					}
					this._Disk_Game.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonHangs.Add(this);
						this._MaDia = value.MaDia;
					}
					else
					{
						this._MaDia = default(string);
					}
					this.SendPropertyChanged("Disk_Game");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_DonHang", ThisKey="MaDonHang", OtherKey="MaDonHang", IsForeignKey=true)]
		public DonHang DonHang
		{
			get
			{
				return this._DonHang.Entity;
			}
			set
			{
				DonHang previousValue = this._DonHang.Entity;
				if (((previousValue != value) 
							|| (this._DonHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonHang.Entity = null;
						previousValue.ChiTietDonHangs.Remove(this);
					}
					this._DonHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonHangs.Add(this);
						this._MaDonHang = value.MaDonHang;
					}
					else
					{
						this._MaDonHang = default(string);
					}
					this.SendPropertyChanged("DonHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Disk_Game")]
	public partial class Disk_Game : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDia;
		
		private bool _ChoThue;
		
		private string _TrangThai;
		
		private System.Nullable<bool> _Deleted;
		
		private string _MaTieuDe;
		
		private EntitySet<ChiTietDonHang> _ChiTietDonHangs;
		
		private EntityRef<TieuDe> _TieuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    partial void OnChoThueChanging(bool value);
    partial void OnChoThueChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    partial void OnMaTieuDeChanging(string value);
    partial void OnMaTieuDeChanged();
    #endregion
		
		public Disk_Game()
		{
			this._ChiTietDonHangs = new EntitySet<ChiTietDonHang>(new Action<ChiTietDonHang>(this.attach_ChiTietDonHangs), new Action<ChiTietDonHang>(this.detach_ChiTietDonHangs));
			this._TieuDe = default(EntityRef<TieuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoThue", DbType="Bit NOT NULL")]
		public bool ChoThue
		{
			get
			{
				return this._ChoThue;
			}
			set
			{
				if ((this._ChoThue != value))
				{
					this.OnChoThueChanging(value);
					this.SendPropertyChanging();
					this._ChoThue = value;
					this.SendPropertyChanged("ChoThue");
					this.OnChoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(100)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTieuDe", DbType="NChar(10)")]
		public string MaTieuDe
		{
			get
			{
				return this._MaTieuDe;
			}
			set
			{
				if ((this._MaTieuDe != value))
				{
					if (this._TieuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTieuDeChanging(value);
					this.SendPropertyChanging();
					this._MaTieuDe = value;
					this.SendPropertyChanged("MaTieuDe");
					this.OnMaTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disk_Game_ChiTietDonHang", Storage="_ChiTietDonHangs", ThisKey="MaDia", OtherKey="MaDia")]
		public EntitySet<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this._ChiTietDonHangs;
			}
			set
			{
				this._ChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_Disk_Game", Storage="_TieuDe", ThisKey="MaTieuDe", OtherKey="MaTieuDe", IsForeignKey=true)]
		public TieuDe TieuDe
		{
			get
			{
				return this._TieuDe.Entity;
			}
			set
			{
				TieuDe previousValue = this._TieuDe.Entity;
				if (((previousValue != value) 
							|| (this._TieuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TieuDe.Entity = null;
						previousValue.Disk_Games.Remove(this);
					}
					this._TieuDe.Entity = value;
					if ((value != null))
					{
						value.Disk_Games.Add(this);
						this._MaTieuDe = value.MaTieuDe;
					}
					else
					{
						this._MaTieuDe = default(string);
					}
					this.SendPropertyChanged("TieuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.Disk_Game = this;
		}
		
		private void detach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.Disk_Game = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonHang")]
	public partial class DonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonHang;
		
		private System.DateTime _HanTraDia;
		
		private System.DateTime _NgayTraDia;
		
		private System.DateTime _NgayThue;
		
		private double _PhiTraTre;
		
		private string _ThanhToanPhiNo;
		
		private string _MaKhachHang;
		
		private EntitySet<ChiTietDonHang> _ChiTietDonHangs;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(string value);
    partial void OnMaDonHangChanged();
    partial void OnHanTraDiaChanging(System.DateTime value);
    partial void OnHanTraDiaChanged();
    partial void OnNgayTraDiaChanging(System.DateTime value);
    partial void OnNgayTraDiaChanged();
    partial void OnNgayThueChanging(System.DateTime value);
    partial void OnNgayThueChanged();
    partial void OnPhiTraTreChanging(double value);
    partial void OnPhiTraTreChanged();
    partial void OnThanhToanPhiNoChanging(string value);
    partial void OnThanhToanPhiNoChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    #endregion
		
		public DonHang()
		{
			this._ChiTietDonHangs = new EntitySet<ChiTietDonHang>(new Action<ChiTietDonHang>(this.attach_ChiTietDonHangs), new Action<ChiTietDonHang>(this.detach_ChiTietDonHangs));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanTraDia", DbType="DateTime NOT NULL")]
		public System.DateTime HanTraDia
		{
			get
			{
				return this._HanTraDia;
			}
			set
			{
				if ((this._HanTraDia != value))
				{
					this.OnHanTraDiaChanging(value);
					this.SendPropertyChanging();
					this._HanTraDia = value;
					this.SendPropertyChanged("HanTraDia");
					this.OnHanTraDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTraDia", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTraDia
		{
			get
			{
				return this._NgayTraDia;
			}
			set
			{
				if ((this._NgayTraDia != value))
				{
					this.OnNgayTraDiaChanging(value);
					this.SendPropertyChanging();
					this._NgayTraDia = value;
					this.SendPropertyChanged("NgayTraDia");
					this.OnNgayTraDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThue", DbType="DateTime NOT NULL")]
		public System.DateTime NgayThue
		{
			get
			{
				return this._NgayThue;
			}
			set
			{
				if ((this._NgayThue != value))
				{
					this.OnNgayThueChanging(value);
					this.SendPropertyChanging();
					this._NgayThue = value;
					this.SendPropertyChanged("NgayThue");
					this.OnNgayThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiTraTre", DbType="Float NOT NULL")]
		public double PhiTraTre
		{
			get
			{
				return this._PhiTraTre;
			}
			set
			{
				if ((this._PhiTraTre != value))
				{
					this.OnPhiTraTreChanging(value);
					this.SendPropertyChanging();
					this._PhiTraTre = value;
					this.SendPropertyChanged("PhiTraTre");
					this.OnPhiTraTreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhToanPhiNo", DbType="NVarChar(50)")]
		public string ThanhToanPhiNo
		{
			get
			{
				return this._ThanhToanPhiNo;
			}
			set
			{
				if ((this._ThanhToanPhiNo != value))
				{
					this.OnThanhToanPhiNoChanging(value);
					this.SendPropertyChanging();
					this._ThanhToanPhiNo = value;
					this.SendPropertyChanged("ThanhToanPhiNo");
					this.OnThanhToanPhiNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_ChiTietDonHangs", ThisKey="MaDonHang", OtherKey="MaDonHang")]
		public EntitySet<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this._ChiTietDonHangs;
			}
			set
			{
				this._ChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonHang", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonHangs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.DonHang = this;
		}
		
		private void detach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.DonHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KH_DatTruoc_TieuDe")]
	public partial class KH_DatTruoc_TieuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _NgayDatHang;
		
		private string _MaKhachHang;
		
		private string _MaTieuDe;
		
		private string _MaDia;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<TieuDe> _TieuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNgayDatHangChanging(System.DateTime value);
    partial void OnNgayDatHangChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaTieuDeChanging(string value);
    partial void OnMaTieuDeChanged();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    #endregion
		
		public KH_DatTruoc_TieuDe()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._TieuDe = default(EntityRef<TieuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDatHang", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDatHang
		{
			get
			{
				return this._NgayDatHang;
			}
			set
			{
				if ((this._NgayDatHang != value))
				{
					this.OnNgayDatHangChanging(value);
					this.SendPropertyChanging();
					this._NgayDatHang = value;
					this.SendPropertyChanged("NgayDatHang");
					this.OnNgayDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTieuDe", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaTieuDe
		{
			get
			{
				return this._MaTieuDe;
			}
			set
			{
				if ((this._MaTieuDe != value))
				{
					if (this._TieuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTieuDeChanging(value);
					this.SendPropertyChanging();
					this._MaTieuDe = value;
					this.SendPropertyChanged("MaTieuDe");
					this.OnMaTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="NChar(10)")]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_KH_DatTruoc_TieuDe", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.KH_DatTruoc_TieuDes.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.KH_DatTruoc_TieuDes.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_KH_DatTruoc_TieuDe", Storage="_TieuDe", ThisKey="MaTieuDe", OtherKey="MaTieuDe", IsForeignKey=true)]
		public TieuDe TieuDe
		{
			get
			{
				return this._TieuDe.Entity;
			}
			set
			{
				TieuDe previousValue = this._TieuDe.Entity;
				if (((previousValue != value) 
							|| (this._TieuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TieuDe.Entity = null;
						previousValue.KH_DatTruoc_TieuDes.Remove(this);
					}
					this._TieuDe.Entity = value;
					if ((value != null))
					{
						value.KH_DatTruoc_TieuDes.Add(this);
						this._MaTieuDe = value.MaTieuDe;
					}
					else
					{
						this._MaTieuDe = default(string);
					}
					this.SendPropertyChanged("TieuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private bool _Deleted;
		
		private string _TenKhachHang;
		
		private EntitySet<DonHang> _DonHangs;
		
		private EntitySet<KH_DatTruoc_TieuDe> _KH_DatTruoc_TieuDes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonHangs = new EntitySet<DonHang>(new Action<DonHang>(this.attach_DonHangs), new Action<DonHang>(this.detach_DonHangs));
			this._KH_DatTruoc_TieuDes = new EntitySet<KH_DatTruoc_TieuDe>(new Action<KH_DatTruoc_TieuDe>(this.attach_KH_DatTruoc_TieuDes), new Action<KH_DatTruoc_TieuDe>(this.detach_KH_DatTruoc_TieuDes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NChar(12) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonHang", Storage="_DonHangs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<DonHang> DonHangs
		{
			get
			{
				return this._DonHangs;
			}
			set
			{
				this._DonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_KH_DatTruoc_TieuDe", Storage="_KH_DatTruoc_TieuDes", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<KH_DatTruoc_TieuDe> KH_DatTruoc_TieuDes
		{
			get
			{
				return this._KH_DatTruoc_TieuDes;
			}
			set
			{
				this._KH_DatTruoc_TieuDes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_KH_DatTruoc_TieuDes(KH_DatTruoc_TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_KH_DatTruoc_TieuDes(KH_DatTruoc_TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TieuDe")]
	public partial class TieuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTieuDe;
		
		private string _TieuDe1;
		
		private int _SoLuongDia;
		
		private double _GiaThue;
		
		private bool _ChoThue;
		
		private int _SoNgayDuocThue;
		
		private string _LoaiDia;
		
		private bool _Deleted;
		
		private EntitySet<Disk_Game> _Disk_Games;
		
		private EntitySet<KH_DatTruoc_TieuDe> _KH_DatTruoc_TieuDes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTieuDeChanging(string value);
    partial void OnMaTieuDeChanged();
    partial void OnTieuDe1Changing(string value);
    partial void OnTieuDe1Changed();
    partial void OnSoLuongDiaChanging(int value);
    partial void OnSoLuongDiaChanged();
    partial void OnGiaThueChanging(double value);
    partial void OnGiaThueChanged();
    partial void OnChoThueChanging(bool value);
    partial void OnChoThueChanged();
    partial void OnSoNgayDuocThueChanging(int value);
    partial void OnSoNgayDuocThueChanged();
    partial void OnLoaiDiaChanging(string value);
    partial void OnLoaiDiaChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public TieuDe()
		{
			this._Disk_Games = new EntitySet<Disk_Game>(new Action<Disk_Game>(this.attach_Disk_Games), new Action<Disk_Game>(this.detach_Disk_Games));
			this._KH_DatTruoc_TieuDes = new EntitySet<KH_DatTruoc_TieuDe>(new Action<KH_DatTruoc_TieuDe>(this.attach_KH_DatTruoc_TieuDes), new Action<KH_DatTruoc_TieuDe>(this.detach_KH_DatTruoc_TieuDes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTieuDe", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTieuDe
		{
			get
			{
				return this._MaTieuDe;
			}
			set
			{
				if ((this._MaTieuDe != value))
				{
					this.OnMaTieuDeChanging(value);
					this.SendPropertyChanging();
					this._MaTieuDe = value;
					this.SendPropertyChanged("MaTieuDe");
					this.OnMaTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TieuDe", Storage="_TieuDe1", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TieuDe1
		{
			get
			{
				return this._TieuDe1;
			}
			set
			{
				if ((this._TieuDe1 != value))
				{
					this.OnTieuDe1Changing(value);
					this.SendPropertyChanging();
					this._TieuDe1 = value;
					this.SendPropertyChanged("TieuDe1");
					this.OnTieuDe1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDia", DbType="Int NOT NULL")]
		public int SoLuongDia
		{
			get
			{
				return this._SoLuongDia;
			}
			set
			{
				if ((this._SoLuongDia != value))
				{
					this.OnSoLuongDiaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDia = value;
					this.SendPropertyChanged("SoLuongDia");
					this.OnSoLuongDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="Float NOT NULL")]
		public double GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this.OnGiaThueChanging(value);
					this.SendPropertyChanging();
					this._GiaThue = value;
					this.SendPropertyChanged("GiaThue");
					this.OnGiaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChoThue", DbType="Bit NOT NULL")]
		public bool ChoThue
		{
			get
			{
				return this._ChoThue;
			}
			set
			{
				if ((this._ChoThue != value))
				{
					this.OnChoThueChanging(value);
					this.SendPropertyChanging();
					this._ChoThue = value;
					this.SendPropertyChanged("ChoThue");
					this.OnChoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayDuocThue", DbType="Int NOT NULL")]
		public int SoNgayDuocThue
		{
			get
			{
				return this._SoNgayDuocThue;
			}
			set
			{
				if ((this._SoNgayDuocThue != value))
				{
					this.OnSoNgayDuocThueChanging(value);
					this.SendPropertyChanging();
					this._SoNgayDuocThue = value;
					this.SendPropertyChanged("SoNgayDuocThue");
					this.OnSoNgayDuocThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDia", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string LoaiDia
		{
			get
			{
				return this._LoaiDia;
			}
			set
			{
				if ((this._LoaiDia != value))
				{
					this.OnLoaiDiaChanging(value);
					this.SendPropertyChanging();
					this._LoaiDia = value;
					this.SendPropertyChanged("LoaiDia");
					this.OnLoaiDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_Disk_Game", Storage="_Disk_Games", ThisKey="MaTieuDe", OtherKey="MaTieuDe")]
		public EntitySet<Disk_Game> Disk_Games
		{
			get
			{
				return this._Disk_Games;
			}
			set
			{
				this._Disk_Games.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_KH_DatTruoc_TieuDe", Storage="_KH_DatTruoc_TieuDes", ThisKey="MaTieuDe", OtherKey="MaTieuDe")]
		public EntitySet<KH_DatTruoc_TieuDe> KH_DatTruoc_TieuDes
		{
			get
			{
				return this._KH_DatTruoc_TieuDes;
			}
			set
			{
				this._KH_DatTruoc_TieuDes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Disk_Games(Disk_Game entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = this;
		}
		
		private void detach_Disk_Games(Disk_Game entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = null;
		}
		
		private void attach_KH_DatTruoc_TieuDes(KH_DatTruoc_TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = this;
		}
		
		private void detach_KH_DatTruoc_TieuDes(KH_DatTruoc_TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = null;
		}
	}
}
#pragma warning restore 1591
